---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dragonfly-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: dragonfly
        group: internal
        url: tcp://dragonfly.database.svc.cluster.local:6379
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
