---
originRequest:
  originServerName: "external.armando.sh"

ingress:
  - hostname: "armando.sh"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.armando.sh"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
