---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kometa-team/kometa/nightly/json-schema/config-schema.json
plex:
  url: http://plex.media.svc.cluster.local
  token: <<PLEX_TOKEN>>
  timeout: 60
  db_cache: 40
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: <<TMDB_API_KEY>>
  cache_expiration: 60
  language: en
  region: US

libraries:
  movies-1080p:
    library_name: Movies
    radarr:
      url: http://radarr-1080p.media.svc.cluster.local
      token: <<RADARR_1080P_KEY>>
    plex:
      url: http://plex.media.svc.cluster.local
      token: <<PLEX_TOKEN>>
      timeout: 60
      db_cache: 40
      clean_bundles: false
      empty_trash: false
      optimize: false
    overlay_files:
      - file: config/overlays/media_info.yml
      - file: config/overlays/audience_rating.yml
  movies-2160p:
    library_name: Movies
    radarr:
      url: http://radarr-2160p.media.svc.cluster.local
      token: <<RADARR_2160P_KEY>>
    plex:
      url: http://plex.media.svc.cluster.local
      token: <<PLEX_TOKEN>>
      timeout: 60
      db_cache: 40
      clean_bundles: false
      empty_trash: false
      optimize: false
    overlay_files:
      - file: config/overlays/media_info.yml
      - file: config/overlays/audience_rating.yml
  tv-1080p:
    library_name: TV Shows
    sonarr:
      url: http://sonarr-1080p.media.svc.cluster.local
      token: <<SONARR_1080P_KEY>>
    plex:
      url: http://plex.media.svc.cluster.local
      token: <<PLEX_TOKEN>>
      timeout: 60
      db_cache: 40
      clean_bundles: false
      empty_trash: false
      optimize: false
    overlay_files:
      - file: config/overlays/media_info.yml
      - file: config/overlays/audience_rating.yml
  tv-2160p:
    library_name: TV Shows
    sonarr:
      url: http://sonarr-2160p.media.svc.cluster.local
      token: <<SONARR_2160P_KEY>>
    plex:
      url: http://plex.media.svc.cluster.local
      token: <<PLEX_TOKEN>>
      timeout: 60
      db_cache: 40
      clean_bundles: false
      empty_trash: false
      optimize: false
    overlay_files:
      - file: config/overlays/media_info.yml
      - file: config/overlays/audience_rating.yml

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  custom_repo: https://github.com/jmxd/Kometa/tree/main
  asset_directory:
  - config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_unfiltered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users:
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  overlay_artwork_filetype: webp_lossy
  overlay_artwork_quality: 90
