# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:pROCKR/R2CNP+kP+zh8DuzGisYTcY0Ccs9KL6cAr0n10u2C9CPiYab53UQHyur+40a2HlfdpN/UfS83HeRtso84I61CedJQCo9VxGBxt/VXFGATA5RgfTBhKygGyiO7z0ek4CNnPDDwueCELX357sGgddR8dmscyhw9HWJARnNPN4K2sfG6AXmHCKCsuU/8J93br0/5dg0vg2+wGnHbfsCmc21QZzNpxKqf6F/DA/A==,iv:DVi0ogCR1hOL31hLf5engkHRBblMwMCw2CJam2zn39k=,tag:fTnb3oMGG31eercMeIodBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fqus3upaaqj85r6gk0rqcru5gxnwmf8c0z6mwvyr5ve684yv8yrsh28sr6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL0M5NTV2Nk0rWmpXMCtU
        eDhpS2MxVzhIZHNjR3RZZC9JakhWclRiRlNNClo2YVo2N01GVUdFZ2QxeTdNVHJC
        SWYvVFVOMndZamhwdUxhUWt2bll2SWsKLS0tIDBhbGlEeEJrT3UzcFk4Sk5NNnpU
        WVVFanRLTENkQUdoL081UUpOZFhnVEEKLaW8GZYnEd/NbXCShQWgqKnyDXAmW3lY
        3X+M/LcH5Gyy3dt9hPKQBaqRqWt55xLt1BOcgQzUusrrOV2iIfPtTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T23:40:51Z"
  mac: ENC[AES256_GCM,data:H2jOQijGblWChjuWLApoJCrp4ybIiTXLz5QVstYkY1Sjy0/kZv+kpguqljLCUhtYHx6mqBThyCOy4oURogYT6viJ6jDcrt6iRH0Qk+zvgpxfyyR2fGV4AWGXJ0XdEpVQ1wAUZ4lu5hZVcGZfvFqYlBILsEIX3Nf1lbM2kl4GYDM=,iv:zjHzpPzHLYjZ5zekGZE23L3SKPVt0ao7Sv6q+u0EQzQ=,tag:RVUTNZGxG2Jo+it+gSfJ8Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
