---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  #- ./agregarr/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./brrpolice/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./seerr/ks.yaml
  #- ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  #- ./tautulli/ks.yaml
