apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: kube-system
      bitwardenServerSDKURL: https://bitwarden-sdk-server.kube-system.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-css-certs
        namespace: kube-system
        key: ca.crt
      organizationID: a8116753-6035-4c6a-baec-b14f00aa9ee3
      projectID: 4e02272d-6c4f-48e9-8de8-b14f00aadd6e
