---
originRequest:
  originServerName: "external.armando.sh"

ingress:
  - hostname: "armando.sh"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.armando.sh"
    service: *svc
  - service: http_status:404
