---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: qbittorrent-secret
    template:
      data:
        WIREGUARD_ADDRESSES: "{{ .WIREGUARD_ADDRESSES }}"
        WIREGUARD_PRESHARED_KEY: "{{ .WIREGUARD_PRESHARED_KEY }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
  dataFrom:
    - extract:
        key: wireguard
    - extract:
        key: xseed
