---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secret
  data:
  - secretKey: WIREGUARD_ADDRESSES
    remoteRef:
      key: "65f0b9cd-7001-4a93-ba74-b1ed00d5f847"
  - secretKey: WIREGUARD_PRESHARED_KEY
    remoteRef:
      key: "534f05ef-dca7-4692-8612-b1ed00e100be"
  - secretKey: WIREGUARD_PRIVATE_KEY
    remoteRef:
      key: "081c839e-1557-4335-8c18-b1ed00d4f957"
  - secretKey: CROSS_SEED_API_KEY
    remoteRef:
      key: "e4652d15-c0fd-493b-ae9e-b272005bccd3"
