---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./emqx/ks.yaml
  - ./home-assistant/ks.yaml
  - ./zigbee2mqtt/ks.yaml
