---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-2160p-config
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
