apiVersion: v1
data:
  config.yaml: |
    commands:
      dry_run: False
      recheck: False
      cat_update: False
      tag_update: True
      rem_unregistered: False
      tag_tracker_error: True
      rem_orphaned: False
      tag_nohardlinks: True
      share_limits: False
      skip_qb_version_check: False
      skip_cleanup: False

    qbt:
      host: "qbittorrent.media.svc.cluster.local:80"

    settings:
      force_auto_tmm: False
      force_auto_tmm_ignore_tags:
        - cross-seed
      tracker_error_tag: issue
      nohardlinks_tag: noHL
      share_limits_tag: ~share_limit
      share_limits_min_seeding_time_tag: MinSeedTimeNotReached
      share_limits_min_num_seeds_tag: MinSeedsNotMet
      share_limits_last_active_tag: LastActiveLimitNotReached
      cat_filter_completed: True
      share_limits_filter_completed: True
      tag_nohardlinks_filter_completed: True
      rem_unregistered_filter_completed: False
      cat_update_all: True
      disable_qbt_default_share_limits: True
      tag_stalled_torrents: True

    directory:
      root_dir: "/media/downloads/torrents/complete/"
      recycle_bin: "/media/downloads/torrents/complete/.RecycleBin"
      #torrents_dir: "/qbit/BT_backup"
      orphaned_dir: "/media/downloads/torrents/complete/orphaned_data"

    cat:
      movies-1080p: "/media/downloads/torrents/complete/movies-1080p"
      movies-2160p: "/media/downloads/torrents/complete/movies-2160p"
      tv-1080p: "/media/downloads/torrents/complete/tv-1080p"
      tv-2160p: "/media/downloads/torrents/complete/tv-2160p"
      music: "/media/downloads/torrents/complete/music"
      cross-seed: "/media/downloads/torrents/complete/cross-seed"

    tracker:
      fearnopeer:
        tag: FearNoPeer
        notifiarr: fearnopeer
      seedpool:
        tag: seedpool
        notifiar: seedpool
      scenetime:
        tag: SceneTime
        notifiarr: scenetime
      connecting|jumbohostpro:
        tag: torrenting
        notifiar: torrenting
      digitalcore:
        tag: DigitalCore
        notifiarr: digitalcore
      torrentleech|tleechreload:
        tag: TorrentLeech
        notifiarr: torrentleech
      other:
        tag: other

    nohardlinks:
      movies-1080p:
      movies-2160p:
      tv-1080p:
      tv-2160p:
      music:

    recyclebin:
      enabled: false
      empty_after_x_days: 60
      save_torrents: false
      split_by_category: true

    orphaned:
      empty_after_x_days: 60
      exclude_patterns:
        - "**/.DS_Store"
        - "**/Thumbs.db"
        - "**/@eaDir"
        - "/data/torrents/temp/**"
        - "**/*.!qB"
        - "**/*_unpackerred"
      max_orphaned_files_to_delete: 50

    apprise:
      api_url:
      notify_url:

    notifiarr:
      apikey:
      instance:

    webhooks:
      error:
      run_start:
      run_end:
      function:
        recheck:
        cat_update:
        tag_update:
        rem_unregistered:
        tag_tracker_error:
        rem_orphaned:
        tag_nohardlinks:
        share_limits:
        cleanup_dirs:
kind: ConfigMap
metadata:
  name: qbit-manage-configmap
  namespace: media
