---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbit-manage
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      qbit-manage:
        type: cronjob
        cronjob:
          schedule: "*/30 * * * *"
          timeZone: "America/Chicago"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: 4.2.1@sha256:e9e7888df6f63fddc8d5326f7bd308d523c181ec28c67357f67167592c41b7b3
            env:
              QBT_CONFIG: "/config/config.yaml"
              TZ: "America/Chicago"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            lifecycle:
              postStart:
                exec:
                  command:
                    [
                      "/bin/sh",
                      "-c",
                      "cp /secret/config.yaml /config/config.yaml",
                    ]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /app/config
          - path: /config
      config-file:
        type: configMap
        name: qbit-manage-configmap
        globalMounts:
          - path: /secret/config.yaml
            subPath: config.yaml
            readOnly: false
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "192.168.20.5"
            path: "/mnt/user/media"
        globalMounts:
          - path: "/media"
