---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: kometa-secret
    template:
      data:
        KOMETA_PLEXTOKEN: "{{ .PLEX_TOKEN }}"
        KOMETA_TMDBAPIKEY: "{{ .TMDB_API_KEY }}"
        KOMETA_RADARR1080PKEY: "{{ .RADARR_1080P_KEY }}"
        KOMETA_RADARR2160PKEY: "{{ .RADARR_2160P_KEY }}"
        KOMETA_SONARR1080PKEY: "{{ .SONARR_1080P_KEY }}"
        KOMETA_SONARR2160PKEY: "{{ .SONARR_2160P_KEY }}"
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: tmdb
    - extract:
        key: radarr
    - extract:
        key: sonarr
