---
groups:
  - name: sonarr-1080p
    rules:
      - alert: SonarrDatabaseIsLocked
        expr: |
          sum by (app) (count_over_time({app=~"sonarr-1080p"} |~ "(?i)database is locked"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical

      - alert: SonarrDatabaseIsMalformed
        expr: |
          sum by (app) (count_over_time({app=~"sonarr-1080p"} |~ "(?i)database disk image is malformed"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
