# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+zCYUZfwtOUw5PLerAv0N97pOxguNXdjmGrXRJ1mdUGryq3b9c72zg==,iv:FSZxobHS4p1osWG9jHBre516S2HA0us2FWvyhVYa+5M=,tag:oCfKf/6XVgEZ5wgulXrV4Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1fqus3upaaqj85r6gk0rqcru5gxnwmf8c0z6mwvyr5ve684yv8yrsh28sr6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL2F5dzN2byt6SUxLUnFQ
        T0krZzJUUS8zSDNUeE1jU1FtKzF4SFBZVDBzCk41eHRJN3R4SGhPK1FPOFdsWnU1
        SDE1dVNKMXhralYybWpsUTlCVTEweGMKLS0tIFB5OU1Uc0FlaW5mYzVScWsvZ0cx
        Ull0amYzU09KZG4zdTBCZ1NyZHFLSmsKaz1iTN56M7zmRK0b7TGp/HG3X6riAn9v
        Or8BquRJeTDJDc7Aj8SGJ/+nW1NcMfzXfJGrle9hj+6pxCh2og5KmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-05T23:40:51Z"
  mac: ENC[AES256_GCM,data:pnDhF8/LCYalwebUWIX1BZmSfQcZPSI3Bt3Mv/myG6Gfrs5TSKNFlmkt0xjblcf8Y22YaP6HD1+TF75EJOGwREVG84vEi3clTsaINhPEhPbrz6EysfrKmw72SaPwlbj0Sn7ErJiOeNQgkbCdOvfl7cNeY0qPqxCTB4rHVSoHrI8=,iv:r0FEPJem8eqd4YpkfBCPNJSw8saa8qzQ29b4U0aXCYI=,tag:/rAFWD/c5BEbNLcxQWkhqw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
