---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiAuth: true,
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: [
              "/media/downloads/torrents/complete/cross-seed"
            ],
            dataDirs: [
              "/media/movies/1080p",
              "/media/movies/2160p",
              "/media/tv/1080p",
              "/media/tv/2160p"
            ],
            linkType: "hardlink",
            matchMode: "partial",
            maxDataDepth: 3,
            outputDir: null,
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://qbittorrent.media.svc.cluster.local",
            radarr: [
              "http://radarr-1080p.media.svc.cluster.local/?apikey={{ .RADARR_1080P_KEY }}",
              "http://radarr-2160p.media.svc.cluster.local/?apikey={{ .RADARR_2160P_KEY }}"
            ],
            skipRecheck: false,
            sonarr: [
              "http://sonarr-1080p.media.svc.cluster.local/?apikey={{ .SONARR_1080P_KEY }}",
              "http://sonarr-2160p.media.svc.cluster.local/?apikey={{ .SONARR_2160P_KEY }}"
            ],
            torznab: [
              2,
              3,
              4,
              7,
              8,
              9,
              10,
              14,
            ].map(i => `http://prowlarr.media.svc.cluster.local/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
            useClientTorrents: true,
            searchCadence: "1 day",
            snatchTimeout: undefined,
            searchTimeout: "45s",
            searchLimit: 300,
            excludeOlder: "2 weeks",
            excludeRecentSearch: "3 days",
            notificationWebhookUrls: [
              "https://notifiarr.com/api/v1/notification/crossSeed/{{ .NOTIFIARR_XSEED_KEY }}"
            ]
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
    - extract:
        key: notifiarr
