endpoints:
  - name: "${APP}"
    group: internal
    url: "${GATUS_SUBDOMAIN:=${APP}}.armando.sh"
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    conditions:
      - "[STATUS] == ${GATUS_STATUS:-200}"
