endpoints:
  - name: "${APP}"
    group: internal
    url: 1.1.1.1
    interval: 1m
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.armando.sh"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
