---
instance:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    version: 2.7.2
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/armando-g/home-ops.git"
    pullSecret: github-deploy-key
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
  kustomize:
    patches:
      - # Add Sops decryption to 'flux-system' Kustomization
        patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
