---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: armando-sh-tls
spec:
  refreshInterval: 1h #
  secretStoreRefs:
    - name: bitwarden-secretsmanager
      kind: SecretStore
  selector:
    secret:
      name: armando-sh-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: armando-sh-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: armando-sh-tls
          property: *key
      metadata:
        note: "animation-unfitted-emporium-quantum-polish-defog"
